export {default as NavBar} from './navbar'
export {default as Main} from './main';
export {default as Movies} from './Movies';
export {default as Search} from './Search';
export {default as InicioSesion} from './inicioSesion';
export {default as RegistroUsuario} from './registroUsuario';
export {default as Perfil} from './Perfil'
export {default as RutaPrivada} from './RutaPrivada'
export {default as RutaProtegida} from './Redirect'
export {default as Footer} from './Footer'
export {default as Series} from './Series'
export {default as Peliculas} from './Peliculas'